service: crypto-exchange-feed

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1
  stage: dev
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetRecords
        - dynamodb:GetShardIterator
        - dynamodb:DescribeStream
        - dynamodb:ListStreams
      Resource: { Fn::GetAtt: [ CryptocurrencyDynamoTable, Arn ] }

functions:
  crypto-feed-scheduler:
    handler: functions/crypto-feed-scheduler.handler
    events:
      - stream:
          type: dynamodb
          arn: { Fn::GetAtt: [ CryptocurrencyDynamoTable, StreamArn ] }
          batchSize: 1

resources:
  Resources:
    CryptocurrencyDynamoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service.name}-${self:provider.stage}-cryptocurrency
        AttributeDefinitions:
          - AttributeName: Symbol
            AttributeType: S
        KeySchema:
          - AttributeName: Symbol
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
