service: crypto-exchange-feed

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1
  stage: dev
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetRecords
        - dynamodb:GetShardIterator
        - dynamodb:DescribeStream
        - dynamodb:ListStreams
      Resource: { Fn::GetAtt: [ CryptocurrencyDynamoTable, Arn ] }

functions:
  crypto-feed-scheduler:
    handler: functions/crypto-feed-scheduler.handler
    vpc:
      subnetIds:
        - { Ref: CryptoFeedsPrivateSubnet }
    events:
      - stream:
          type: dynamodb
          arn: { Fn::GetAtt: [ CryptocurrencyDynamoTable, StreamArn ] }

resources:
   - ${file(cloudformation-resources/dynamodb-table.yml)}
   - ${file(cloudformation-resources/ecs-cluster.yml)}
   - ${file(cloudformation-resources/networking.yml)}
