service: crypto-exchange-feed

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1
  stage: dev
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetRecords
        - dynamodb:GetShardIterator
        - dynamodb:DescribeStream
        - dynamodb:ListStreams
      Resource: { Fn::GetAtt: [ CryptocurrencyDynamoTable, Arn ] }
    - Effect: Allow
      Action:
        - ecs:ListTasks
        - ecs:DescribeTask
      Condition:
          ArnEquals: { 'ecs:cluster': { Fn::GetAtt: CryptoFeedsECSCluster.Arn } }
      Resource: '*'
    - Effect: Allow
      Action:
        - ecs:RunTask
      Condition:
          ArnEquals: { 'ecs:cluster': { Fn::GetAtt: CryptoFeedsECSCluster.Arn } }
      Resource: { Ref: CryptoFeedsECSCTaskDefinition }

functions:
  crypto-feed-scheduler:
    handler: functions/crypto-feed-scheduler.handler
    vpc:
      subnetIds:
        - { Ref: CryptoFeedsPrivateSubnet }
    events:
      - stream:
          type: dynamodb
          arn: { Fn::GetAtt: [ CryptocurrencyDynamoTable, StreamArn ] }
    environment:
      CRYPTOFEEDS_ECS_CLUSTER: { Ref: CryptoFeedsECSCluster }

resources:
   - ${file(cloudformation-resources/dynamodb-table.yml)}
   - ${file(cloudformation-resources/ecs-cluster.yml)}
   - ${file(cloudformation-resources/networking.yml)}
