Resources:
  EcrRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: ${self:custom.cryptofeed_docker_image}
  CryptoFeedsECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: ${self:service.name}-${self:provider.stage}-cryptofeeds
  CryptoFeedsECSCTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: { Fn::GetAtt: CryptoFeedsECSCTaskExecutionRole.Arn }
      Cpu: 256
      Memory: 0.5GB
      NetworkMode: awsvpc
      ContainerDefinitions:
        -
          Image:
            Fn::Join:
              - '.'
              - - Ref: AWS::AccountId
                - dkr.ecr
                - Ref: AWS::Region
                - amazonaws.com/${self:custom.cryptofeed_docker_image}:latest
          Name: ${self:custom.cryptofeed_container_name}
          Memory: 128
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: { Ref: CryptoFeedsLogGroup }
              awslogs-region: eu-west-1
              awslogs-stream-prefix: cryptofeed
  CryptoFeedsLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: ${self:service.name}-${self:provider.stage}-cryptofeeds
      RetentionInDays: 1
  CryptoFeedsECSCTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: [ ecs-tasks.amazonaws.com ]
          Action: [ 'sts:AssumeRole' ]
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
